# v2 syntax
version: '2'

# Named volumes
volumes:
  # MongoDB Data
  app-mongodb-data:
    driver: local

services:
  # MongoDB
  mongodb:
    image: sameersbn/mongodb
    container_name: app-mongodb
    ports:
      - "28002:27017"
    volumes:
      - app-mongodb-data:/var/lib/mongodb
    restart: always
