# v2 sintax
version: '2'

services:
  MongoDB:
    container_name: mongo-app
    image: sameersbn/mongodb:latest
    ports:
      - "28002:27017"
    volumes:
      - ./storage/mongodb:/var/lib/mongodb
    restart: always
